FROM fluent/fluentd:v1.11-debian

USER root
RUN gem install elasticsearch -v 7.9
RUN gem install fluent-plugin-elasticsearch
RUN gem install fluent-plugin-rewrite-tag-filter
RUN gem install fluent-plugin-multi-format-parser
